services:
  - type: web
    name: xray-fracture-detection-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && bash scripts/fetch_model.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: MODEL_URL
        sync: false

